/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Howtouse.java
 *
 * Created on Mar 19, 2011, 7:23:13 PM
 */

package gui;

import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author rhapsodixx
 */
public class Howtouse extends javax.swing.JFrame {

    /** Creates new form Howtouse */
    public Howtouse() {
        initComponents();
        this.setIconImage(new ImageIcon("src/gui/icon.png").getImage());
        setLocation((int) Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2 - (int) this.getSize().getWidth()/2, (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2 - (int) this.getSize().getHeight()/2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Market Basket Analyzer | How To Use");
        setResizable(false);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Start the program using the Start Analysis menu.\n\nThe analysis performed in analysis process form, user will enter a result table prefix that will be used to store the results of the analysis. Users can also specify the transactions to be selected by date, simply by check sign \"by date\" and then fill in the date of the \"from\" to \"Until\".\n\nIn this step users will be also specifying the algorithm to be used as well as input parameter values ​​required for the algorithm, simply fill in the available text field and then pressing the submit button.\n\nClick the Start button to start the process.\n\nOnce the process is completed, user can view results by pressing the view result. Use the Save button to save the log analysis results in the log area.");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Howtouse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables

}
