/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainGUI.java
 *
 * Created on 11 Mar 11, 9:03:13
 */
package gui;

import java.awt.Toolkit;
import javax.swing.ImageIcon;
import model.controller;

/**
 *
 * @author Panji
 */
public class MainGUI extends javax.swing.JFrame {
    private boolean useexisting = false;

    /** Creates new form MainGUI */
    public MainGUI() {
        initComponents();
        this.setIconImage(new ImageIcon("src/gui/icon.png").getImage());
        setLocation((int) Toolkit.getDefaultToolkit().getScreenSize().getWidth()/2 - (int) this.getSize().getWidth()/2, (int) Toolkit.getDefaultToolkit().getScreenSize().getHeight()/2 - (int) this.getSize().getHeight()/2);
        controller c = new controller();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewresultButton = new javax.swing.JButton();
        startanalysisButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dbSetting = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        datacleaningButton = new javax.swing.JMenuItem();
        transactionTemp = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        howtoMenu = new javax.swing.JMenuItem();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Market Basket Analyzer");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        viewresultButton.setText("View Result");
        viewresultButton.setToolTipText("Click this to view anaysis result.");
        viewresultButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        viewresultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewresultButtonActionPerformed(evt);
            }
        });

        startanalysisButton.setText("Start Analysis");
        startanalysisButton.setToolTipText("Click this button to start an analysis!");
        startanalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startanalysisButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewresultButton, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(startanalysisButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewresultButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startanalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/front.png"))); // NOI18N
        jLabel1.setToolTipText("Panji Gautama -  2011");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("Setting");

        dbSetting.setText("Database Connection");
        dbSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbSettingActionPerformed(evt);
            }
        });
        jMenu1.add(dbSetting);

        jMenuItem1.setText("Delete Result");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        datacleaningButton.setText("Data Cleaning");
        datacleaningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datacleaningButtonActionPerformed(evt);
            }
        });
        jMenu1.add(datacleaningButton);

        transactionTemp.setText("Use Existing Transaction Temp");
        transactionTemp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                transactionTempItemStateChanged(evt);
            }
        });
        jMenu1.add(transactionTemp);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        howtoMenu.setText("How To Use");
        howtoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howtoMenuActionPerformed(evt);
            }
        });
        jMenu2.add(howtoMenu);

        aboutMenu.setText("About");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuActionPerformed(evt);
            }
        });
        jMenu2.add(aboutMenu);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewresultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewresultButtonActionPerformed
        // TODO add your handling code here:
        new ViewResult().setVisible(true);
        dispose();
    }//GEN-LAST:event_viewresultButtonActionPerformed

    private void startanalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startanalysisButtonActionPerformed
        // TODO add your handling code here:
        new AnalysisProsesUI(useexisting).setVisible(true);
        dispose();
    }//GEN-LAST:event_startanalysisButtonActionPerformed

    private void dbSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbSettingActionPerformed
        // TODO add your handling code here:
        new dbsetting().setVisible(true);
    }//GEN-LAST:event_dbSettingActionPerformed

    private void aboutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuActionPerformed
        // TODO add your handling code here:
        new About().setVisible(true);
    }//GEN-LAST:event_aboutMenuActionPerformed

    private void howtoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howtoMenuActionPerformed
        // TODO add your handling code here:
        new Howtouse().setVisible(true);
    }//GEN-LAST:event_howtoMenuActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new RuleDelete().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void transactionTempItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_transactionTempItemStateChanged
        // TODO add your handling code here:
        Object source = evt.getItemSelectable();
        if (source == transactionTemp) {
            useexisting = true;
            System.out.println(useexisting);
        }
        if (evt.getStateChange() == java.awt.event.ItemEvent.DESELECTED) {
            useexisting = false;
            System.out.println(useexisting);
        }
    }//GEN-LAST:event_transactionTempItemStateChanged

    private void datacleaningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datacleaningButtonActionPerformed
        // TODO add your handling code here:
        new CleaningData().setVisible(true);
    }//GEN-LAST:event_datacleaningButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenuItem datacleaningButton;
    private javax.swing.JMenuItem dbSetting;
    private javax.swing.JMenuItem howtoMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton startanalysisButton;
    private javax.swing.JCheckBoxMenuItem transactionTemp;
    private javax.swing.JButton viewresultButton;
    // End of variables declaration//GEN-END:variables
}
